name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  pre-commit:
    name: Pre-commit
    runs-on: ubuntu-20.04
    continue-on-error: true

    steps:
      - name: Checkout
        uses: actions/checkout@v3.2.0

      - name: Install Python
        uses: actions/setup-python@v4.4.0
        with:
          python-version: "3.11"

      - name: Run pre-commit checks
        uses: pre-commit/action@v3.0.0


  ci:
    name: ${{ matrix.name }} - ${{ matrix.py_version }}
    runs-on: ubuntu-20.04
    env:
      TOX_ENV: ${{ matrix.tox_env }}

    strategy:
      fail-fast: false
      matrix:
        name:
          - Sanity
          - Unit

        py_version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"

        include:
          - name: Sanity
            tox_env: sanity

          - name: Unit
            tox_env: unit

    steps:
      - name: Checkout repsository
        uses: actions/checkout@v3.2.0
        with:
          fetch-depth: 0

      - name: Display build environment
        run: printenv

      - name: Install Python ${{ matrix.py_version }}
        uses: actions/setup-python@v4.4.0
        with:
          python-version: ${{ matrix.py_version }}

      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox -c tests/requirements/dev.txt

      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/cache@v3.2.2
        with:
          path: |
            ~/.cache/pip
            .tox/
          key: ${{ runner.os }}-env-${{ matrix.py_version }}-${{ hashFiles('tests/requirements/dev.txt') }}

      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          tox run --notest

      - name: Run tests
        run: tox run

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.1
        if: contains(env.TOX_ENV, 'unit')
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          name: Python-${{ matrix.py_version}}
          fail_ci_if_error: true
