name: pre-commit

on:
  pull_request:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      with:
        python-version: '3.8'
    - uses: pre-commit/action@v2.0.0
      uses: actions/checkout@v3
      uses: pre-commit/action@v3.0.0
